# Generated by Django 5.2.6 on 2025-12-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='year',
            new_name='date',
        ),
    ]
