# Generated by Django 5.2.6 on 2025-12-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_year_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='repository',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
