# Generated by Django 5.2.6 on 2025-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_repository_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registry_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
