# Generated by Django 5.2.6 on 2025-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_registry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_image',
            field=models.ImageField(blank=True, null=True, upload_to='invites/'),
        ),
    ]
