# Generated by Django 5.2.6 on 2025-12-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_invitation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invitation_image',
        ),
    ]
