# Generated by Django 5.2.6 on 2025-12-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_remove_event_repository_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('attending', models.BooleanField(blank=True, null=True)),
                ('meal_choice', models.CharField(blank=True, choices=[('steak', 'Steak'), ('chicken', 'Chicken'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
        ),
    ]
