# Generated by Django 5.2.6 on 2025-12-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_repository_alter_event_date'),
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(max_length=254)),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.event')),
            ],
        ),
    ]
