# Generated by Django 5.2.6 on 2025-12-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_guestinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plus_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='code',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('chicken', 'Chicken'), ('beef', 'Beef'), ('fish', 'Fish'), ('veg', 'Vegetarian')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='GuestInvite',
        ),
    ]
