# Generated by Django 5.2.6 on 2025-12-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_guest_plus_one_alter_guest_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plus_one_meal_choice',
            field=models.CharField(blank=True, choices=[('chicken', 'Chicken'), ('beef', 'Beef'), ('fish', 'Fish'), ('veg', 'Vegetarian')], max_length=20),
        ),
    ]
